name: Build And Deploy Plog

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out git repository
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable

      - name: Build Rust Project
        run: cargo build --release

      - name: Run Rust Project
        run: ./target/release/plog

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./public

